#!/bin/bash

declare -a homedealTerms=("[5-6] offertes"
                          "[5-6] offerte"
                          "[5-6] verschillende"
                          "[5-6] betrouwbare"
                          "[5-6] gratis"
                          "[5-6] specialisten"
                          "[5-6] hoveniers"
                          "[5-6] hoveniersbedrijven"
                          "[5-6] erkende hoveniersbedrijven"
                          "[5-6] geselecteerde hoveniers"
                          "[5-6] bedrijven"
                          "[5-6] aannemer offertes"
                          "[5-6] dakkapelspecialisten"
                          "[5-6] dakkapel"
                          "[5-6] dakkapel offertes"
                          "[5-6] dakkapellen specialisten"
                          "[5-6] prijsopgave"
                          "[5-6] prijsopgaves"
                          "[5-6] prijsopgaven"
                          "[5-6] diverse prijsopgaves"
                          "[5-6] aanbieders"
                          "[5-6] aanbiedingen"
                          "[5-6] airco offertes"
                          "[5-6] cv-installateurs"
                          "[5-6] cv-installatiebedrijven"
                          "[5-6] dakdekkersbedrijven"
                          "[5-6] gevelbekleding offertes"
                          "[5-6] glasspecialisten"
                          "[5-6] installateurs"
                          "[5-6] kozijnspecialisten"
                          "[5-6] leveranciers"
                          "[5-6] lokale bedrijven"
                          "[5-6] lokale beveiligingsbedrijven"
                          "[5-6] lokale verhuisbedrijven"
                          "[5-6] professionele dakwerkers"
                          "[5-6] rolluiken"
                          "[5-6] schilders"
                          "[5-6] schildersbedrijven"
                          "[5-6] stratenmakers"
                          "[5-6] stucadoors"
                          "[5-6] stukadoorbedrijven"
                          "[5-6] tegelzetters"
                          "[5-6] tuinmannen"
                          "[5-6] vakkundige"
                          "[5-6] verhuisbedrijven"
                          "[5-6] verhuisoffertes"
                          "[5-6] vrijblijvende offertes"
                          "[5-6] vrijblijvende prijsopgaves"
                          "tot wel [5-6]"
                          "van maximaal [5-6]"
                          "tot maximaal [5-6]"
                          "up to [5-6]")



declare -a skydreamsTerms=("[5-6] preventivi"
                            "[5-6] price offers"
                            "[5-6] quotations"
                            "[5-6] quotes"
                            "[5-6] spécialistes"
                            "[5-6] proposte"
                            "[5-6] prospetti"
                            "[5-6] entreprises"
                            "[5-6] offres"
                            "[5-6] aziende"
                            "[5-6] déménageurs"
                            "[5-6] devis d'entreprises"
                            "[5-6] devis de déménageurs"
                            "[5-6] devis de spécialistes"
                            "[5-6] devis"
                            "[5-6] emails from local companies"
                            "[5-6] local companies"
                            "[5-6] emails with competitive quotes"
                            "[5-6] estimates"
                            "[5-6] esperti del settore"
                            "[5-6] estimations d'entreprises"
                            "[5-6] heating companies"
                            "[5-6] movers"
                            "[5-6] moving companies"
                            "[5-6] no obligation quotes"
                            "[5-6] no-obligation quotes"
                            "[5-6] non-binding quotes"
                            "[5-6] offers"
                            "[5-6] preventivi da aziende diverse"
                            "[5-6] professional"
                            "[5-6] quotes"
                            "[5-6] removal specialists"
                            "[5-6] replies in your inbox from local"
                            "[5-6] risposte da aziende"
                            "[5-6] sociétés"
                            "[5-6] trusted, local companies"
                            "[5-6] worldwide removal companies"
                            "[5-6] zonnepanelen specialisten"
                            "[5-6] Offertes"
                            "[5-6] companies"
                            "[5-6] verhuisbedrijvenuit"
                            "[5-6] keuzes te staan om het rolluik")

cd /vagrant/www/wordpress-homedeal/htdocs

for pattern in "${homedealTerms[@]}"
do
    echo "$pattern -> ${pattern/\[5-6\]/[default_number_quotes]}"
    wp search-replace --include-columns=post_content --regex --network "\b$pattern\b" "${pattern/\[5-6\]/[default_number_quotes]}" *_posts
done

cd /vagrant/www/wordpress-skydreams/htdocs

allTerms=("${homedealTerms[@]}" "${skydreamsTerms[@]}")

for pattern in "${allTerms[@]}"
do
    echo "$pattern -> ${pattern/\[5-6\]/[default_number_quotes]}"
    wp search-replace --include-columns=post_content --regex --network "\b$pattern\b" "${pattern/\[5-6\]/[default_number_quotes]}" *_posts
done
